advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view(), name = 'index'),
    path('basic_app/', include('basic_app.urls', namespace='basic_app'))
]

advcbv/basic_app/urls.py
from django.urls import path
from basic_app import views


app_name = 'basic_app'

urlpatterns = [

    path('',views.SchoolListView.as_view(),name='list'),
    path('students/',views.StudentListView.as_view(),name='slist'),
    path('<int:pk>/',views.SchoolDetailView.as_view(),name='detail'),
    path('students/<int:pk>/',views.StudentDetailView.as_view(),name='sdetail'),
    path('create/', views.SchoolCreateView.as_view(),name='create'),
    path('screate/', views.StudentCreateView.as_view(),name='screate'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name='delete'),
    path('students/update/<int:pk>/', views.StudentUpdateView.as_view(), name='supdate'),
    path('students/delete/<int:pk>/', views.StudentDeleteView.as_view(), name='sdelete'),

]

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk':self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age =models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:sdetail", kwargs={'pk': self.pk})

advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View, TemplateView,
                                    ListView, DetailView,
                                    CreateView, UpdateView,
                                    DeleteView)
from . import models
from django.urls import reverse_lazy

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'BASIC INJECTION!'
        return context

class SchoolListView(ListView):
    #if we want to change name of list:
    context_object_name = 'schools'
    model = models.School
    #it returns school_list :)

class StudentListView(ListView):
    model = models.Student
    #student_list

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'


class StudentDetailView(DetailView):
    context_object_name = 'student_detail'
    model = models.Student
    template_name = 'basic_app/student_detail.html'


class SchoolCreateView(CreateView):
    fields = ('name', 'principal','location')
    model = models.School

class StudentCreateView(CreateView):
    fields = ('name', 'age','school')
    model = models.Student

class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School

class StudentUpdateView(UpdateView):
    fields = ('name', 'age', 'school')
    model = models.Student

class SchoolDeleteView(DeleteView):
    model =models.School
    success_url = reverse_lazy("basic_app:list")

class StudentDeleteView(DeleteView):
    model = models.Student
    success_url = reverse_lazy("basic_app:slist")

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top'>
      <ul class='nav navbar-nav'>
        <li><a class ='navbar-link' href="{% url 'index' %}">Home</a></li>
        <li><a class ='navbar-link' href="{% url 'basic_app:list' %}">Schools</a></li>
        <li><a class ='navbar-link' href="{% url 'basic_app:slist' %}">Students</a></li>
        <li><a class ='navbar-link' href="{% url 'admin:index' %}">Admin</a></li>
        <li><a href="#"></a></li>
      </ul>

    </nav>







    {% block body_block %}
    {%endblock%}

  </body>
</html>

advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html"%}
{%block body_block%}
<h1>Delete {{school.name}} ?</h1>
<form method="post">
  {%csrf_token%}
  <input type="submit" class ='btn btn-danger'value="Delete">
  <a href="{%url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>

{% endblock%}

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html"%}
{% block body_block%}
<div class="jumbotron">

  <h1>Welcome to the School Detail Page</h1>
  <h2>School Details:</h2>
  <p>Name: {{school_detail.name}}</p>
  <p>Principal: {{school_detail.principal}}</p>
  <p>Location: {{school_detail.location}}</p>
  <h3>Students:</h3>
  {% for student in school_detail.students.all %}

  <p>{{student.name}} who is {{student.age}} years old.</p>
  {% endfor %}

</div>
<div class="container">
    <p><a class ='btn btn-warning' href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
    <p><a class ='btn btn-danger' href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a></p>
    <a href="{%url 'basic_app:list' %}">Back </a>

</div>
{% endblock %}

advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html"%}
{%block body_block%}

<h1>
  {%if not form.instanse.pk %}
  Create School
  {%else%}
  Update School
  {%endif%}
</h1>

<form method="post">
  {%csrf_token%}
  {{form.as_p}}
  <input type="submit" class="btn btn-primary" value="Submit">
</form>

{%endblock%}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html"%}

{% block body_block%}
<h1>Welcome to list of all the Schools</h1>
  <ol>
    {% for school in schools%}
    <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
    {% endfor %}
  </ol>
  <a class="btn btn-button" href="{%url 'basic_app:create' %}">Create new School </a>

{% endblock %}

advcbv/basic_app/templates/basic_app/student_confirm_delete.html
{% extends "basic_app/basic_app_base.html"%}
{%block body_block%}
<h1>Delete {{student.name}} ?</h1>
<form method="post">
  {%csrf_token%}
  <input type="submit" class ='btn btn-danger'value="Delete">
  <a href="{%url 'basic_app:sdetail' pk=student.pk %}">Cancel</a>
</form>

{% endblock%}

advcbv/basic_app/templates/basic_app/student_detail.html
{% extends "basic_app/basic_app_base.html"%}
{% block body_block%}
<div class="jumbotron">

  <h1>Welcome to the Student Detail Page</h1>
  <h2>Student Details:</h2>
  <p>Name: {{student_detail.name}}</p>
  <p>Age: {{student_detail.age}}</p>
  <p>School: {{student_detail.school}}</p>
</div>
</div>
<div class="container">
    <p><a class ='btn btn-warning' href="{% url 'basic_app:supdate' pk=student_detail.pk %}">Update</a></p>
    <p><a class ='btn btn-danger' href="{% url 'basic_app:sdelete' pk=student_detail.pk %}">Delete</a></p>
    <a href="{%url 'basic_app:slist' %}">Back </a>

</div>
{% endblock %}

advcbv/basic_app/templates/basic_app/student_form.html
{% extends "basic_app/basic_app_base.html"%}
{%block body_block%}

<h1>
  {%if not form.instanse.pk %}
  Create Student
  {%else%}
  Update Student
  {%endif%}
</h1>

<form method="post">
  {%csrf_token%}
  {{form.as_p}}
  <input type="submit" class="btn btn-primary" value="Submit">
</form>

{%endblock%}

advcbv/basic_app/templates/basic_app/student_list.html
{% extends "basic_app/basic_app_base.html"%}

{% block body_block%}
<h1>Welcome to list of all the Students</h1>
  <ol>
    {% for student in student_list%}
    <h2><li><a href="{{student.id}}">{{student.name}}</a></li></h2>
    {% endfor %}
  </ol>
  <a class="btn btn-button" href="{%url 'basic_app:screate' %}">Create new Student </a>

{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top'>
      <ul class='nav navbar-nav'>
        <li><a class ='navbar-link' href="{% url 'index' %}">Home</a></li>
        <li><a class ='navbar-link' href="{% url 'basic_app:list' %}">Schools</a></li>
        <li><a class ='navbar-link' href="{% url 'basic_app:slist' %}">Students</a></li>
        <li><a class ='navbar-link' href="{% url 'admin:index' %}">Admin</a></li>
        <li><a href="#"></a></li>
      </ul>

    </nav>







    {% block body_block %}
    {%endblock%}

  </body>
</html>

advcbv/templates/index.html
{% extends "base.html"%}
    {% block body_block %}
    <div class='jumbotron'>
      <h1>School CRUD</h1>
      <h3>Basic app where u can Create, Read, Update or Remove information about Schools or Students.</h3>

    </div>
    {%endblock%}